### ISSUE TITLE
Enable/disable alert rules

### ISSUE THREAD

**Issue by nsano-rururu** [nsano-rururu/elastalert-kibana-plugin#47]

**Comment by Zhang21** [comment]
Yes, or can silence alerts by this plugin web?

**Comment by nsano-rururu** [comment]
This repository is a fork, not the developer. Therefore, the answer is unofficial. Please note that.

In conclusion, no.
It seems that bitsensor is internally calling ElastAlert Server, which is the ElastAlert API created by Node.js. However, the silence API is not implemented in the one made by bitsensor.
It has been added to [johnsusek/elastalert-server](https://github.com/johnsusek/elastalert-server) that is a fork of Elast Alert Server of bitsensor, so I think that it can be modified by calling that API. I will.
The problem is that I'm the maintainer of [johnsusek/elastalert-server](https://github.com/johnsusek/elastalert-server) and [johnsusek/praeco](https://github.com/johnsusek/praeco) The situation is that we cannot take the time to repair elastalert-kibana-plugin.

**Comment by nsano-rururu** [comment]
ElastAlert implements silence.

**Comment by nsano-rururu** [comment]
I'm not satisfied with this answer. I do not understand

**Comment by nsano-rururu** [comment]
Since we decided to use discussions, we will close existing issues.
https://github.com/nsano-rururu/elastalert-kibana-plugin/discussions
