### ISSUE TITLE
Add explain why fork was created to README (or add pull request)

### ISSUE THREAD

**Issue by vgavro** [nsano-rururu/elastalert-kibana-plugin#63]
I can't see pull request in original repository  bitsensor/elastalert-kibana-plugin - is it's abandoned?
thanks for your work.
PS. like I see - yes, it is https://github.com/bitsensor/elastalert-kibana-plugin/issues/151
I'm sure you should add link to this ticket to you README, at least.
IF old repository is abandoned - please create PULL REQUEST for their README with link to this NEW repository.
And maybe create ticket to elastalert to change their links?
Thanks!

**Comment by nsano-rururu** [comment]
@vgavro 

Proposed Thank you.
We plan to update the README this weekend.
We will not make pull requests to ElastAlert.
The reason is that ElastAlert is likely to end support later this year.

Status of the elastalert project # 2911

>Qmando commented 2 days ago
>Hi, sorry about the inactivity in this project, we are not currently doing any active development on it. All of the branches, including beta, should be ignored, and are likely already merged.
>
>I do plan on doing a final round of bug fixes and cleanup before we officially end support, probably sometime this year.
