### ISSUE TITLE
Migrating from legacy plugins to the new platform

### ISSUE THREAD

**Issue by nsano-rururu** [nsano-rururu/elastalert-kibana-plugin#69]
As Kibana 7.10.0 is removing the functions used by the legacy plugins, we have to start migrating elastalert-kibana-plugin to a new platform.

This link shows the requirements and the process to do this migration:
Migrating legacy plugins to the new platform -[link](https://www.elastic.co/guide/en/kibana/7.x/migrating-legacy-plugins.html)

Node.js version v10.20.0. → v10.22.1.

https://www.elastic.co/guide/en/kibana/7.10/breaking-changes-7.10.html
```
Legacy plugins support removededit
The legacy plugin system and the legacy plugin API have been removed. Legacy plugin owners should migrate their plugins to the Kibana Platform plugin API.

via #77599

Support added for Kibana Platform pluginsedit
The bin/kibana-plugin CLI has been updated to work with the new Kibana Platform plugin format instead of the legacy plugin format.

via #74604
```

**Comment by nsano-rururu** [comment]
If we cannot respond, support will end.

**Comment by nsano-rururu** [comment]
We plan to create a plugin template to migrate the current implementation to the created template.

Node.js version v10.20.0. → v10.22.1.

scripts/generate_plugin your_plugin_name. 

https://medium.com/query-ai/how-to-set-up-the-kibana-plugin-development-environment-f64ad8aceb80

**Comment by nsano-rururu** [comment]
Currently, elastalert is in hibernation, so we will not add or modify functions.

**Comment by nsano-rururu** [comment]
If the development of the currently dormant elastalert is finished, the development will be finished without the support of new kibana.

**Comment by nsano-rururu** [comment]
https://github.com/elastic/kibana/blob/v7.10.0/src/core/MIGRATION.md
https://github.com/elastic/kibana/blob/v7.10.0/src/core/MIGRATION_EXAMPLES.md

**Comment by ch-bas** [comment]
Hi @nsano-rururu , maybe this #125  can help.

**Comment by nsano-rururu** [comment]
https://github.com/nsano-rururu/elastalert-kibana-plugin/tree/migrating-plugin-new-platform

**Comment by nsano-rururu** [comment]
"const uri = process.env.PROTOCOL +': //' + process.env.HOSTNAME + process.env.PORT;" is described in server / routes / index.ts. Why do you do this? I can't understand. The original process was to get the value from kibana.yml. I do not know what you mean.

**Comment by ch-bas** [comment]
In the new Kibana's Platfrom, I couldn’t find how to read the values defined in 'kibana.yml', this is why I used environment variables.

**Comment by nsano-rururu** [comment]
>In the new Kibana's Platfrom, I couldn’t find how to read the values defined in 'kibana.yml', this is why I used environment variables.

I understand. I will also look for it.

**Comment by nsano-rururu** [comment]
@ch-bas 

The following reports were received from users. Did you not even check the operation?
Are you in the process of making it?

---

I tried that repo with the following Dockerfile and it doesn't seem to work
```
FROM docker.elastic.co/kibana/kibana:7.10.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip --allow-root
```

Here's the error I see
```
Attempting to transfer from https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip
Transferring 90230 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "Invalid plugin name [elastalert-kibana-plugin] in kibana.json, expected it to be valid camelCase"
The command '/bin/sh -c /usr/share/kibana/bin/kibana-plugin install https://github.com/ch-bas/elastalert-kibana-plugin/releases/download/1.3.1/elastalert-kibana-plugin-7.10.0.zip --allow-root' returned a non-zero code: 70
```

**Comment by ch-bas** [comment]
Hi @nsano-rururu , I did not receive any kind of issue or notification about that issue, but this can be simply fixed.

**Comment by nsano-rururu** [comment]
@ch-bas

One more point to confirm. Is the 7.10 compatible version of elastalert-kibana-plugin confirmed on the screen whether rules can be created, tested, and deleted by starting with the combination of Elasitcsearch 7.10, Kibana 7.10, and ElastAlertServer? If you don't know ElastAlertServer, there is [Sample](https://github.com/nsano-rururu/elastalert-kibana-plugin/wiki/docker-compose-sample) that was used for operation check in the previous version, so I think it will be helpful.

**Comment by ch-bas** [comment]
I remember that I tested creating and displaying the rules and it worked fine, I will try to find time to test the rest of the CRUD operation, but I don't expect to do it any time soon. Thanks!

**Comment by Karql** [comment]
#143

**Comment by nsano-rururu** [comment]
Since we decided to use discussions, we will close existing issues.
https://github.com/nsano-rururu/elastalert-kibana-plugin/discussions
